name: client
description: Very cool project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-171.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  queries_repository:
    path: ./packages/queries_repository
  flutter_bloc: ^8.1.1
  auto_route: ^5.0.2
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  freezed: ^2.2.1

flutter:
  uses-material-design: true